# Generated by Django 5.0.4 on 2024-04-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
